M48
; DRILL file {KiCad (6.0.6)} date Wed Jun 21 15:59:25 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-06-21T15:59:25+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
%
G90
G05
T1
X178.45Y-93.841
X178.45Y-98.691
T2
X181.48Y-93.541
X181.48Y-98.991
T0
M30
